FROM registry.fedoraproject.org/fedora-minimal:42

RUN dnf install -y procps-ng inotify-tools stress stress-ng vim vim-powerline powerline tmux tmux-powerline && \
    dnf clean all && \
    rm -rf /var/cache/dnf/*

COPY .bashrc .tmux.conf .vimrc /root/

ENTRYPOINT ["/usr/bin/tmux", "new", "-A"]
