#!/bin/sh

GO_VERSION=`go version`
cat <<EOF
This is a S2I ${GO_VERSION} CentOS 7 base image:
To use it, install S2I: https://github.com/openshift/source-to-image
Sample invocation:
  
  $ s2i build . docker.io/tnozicka/s2i-centos7-golang docker.io/tnozicka/openshift-acme -e APP_URI=github.com/tnozicka/openshift-acme --runtime-image=docker.io/tnozicka/s2i-centos7-golang-runtime --runtime-artifact=/opt/app-root/src/bin/app:bin/

You can then run the resulting image via:
$ docker run -p 5000:5000 go-test-app
EOF
