FROM registry.fedoraproject.org/fedora-minimal:44

SHELL ["/usr/bin/bash", "-euExo", "pipefail", "-O", "inherit_errexit", "-c"]

# Install a minimal subset of packages that *every* runtime image needs.
RUN microdnf update -y && \
    microdnf install -y jq tar gzip findutils util-linux-core && \
    microdnf clean all && \
    rm -rf /var/cache/dnf/*

ENTRYPOINT []
CMD ["/usr/bin/bash"]
