FROM debug

RUN dnf install -y hugo npm helm dos2unix yamllint pip buildah podman skopeo opentofu detox rust cargo gnuplot-minimal && \
    dnf clean all && \
    rm -rf /var/cache/dnf/* && \
    go install github.com/github/github-mcp-server/cmd/github-mcp-server@v1.4.0 && \
    go install github.com/cli/cli/v2/cmd/gh@v2.95.0

RUN platform="$( curl --fail --retry 5 --retry-all-errors -L https://static.devin.ai/cli/current/manifest.json | jq -ec --arg target "$( arch )-unknown-linux" '.platforms[$target]' )" && \
    curl --fail --retry 5 --retry-all-errors -L "$( jq -er '.url' <<< "${platform}" )" -o /tmp/devin.tar.gz && \
    sha256sum -c <<< "$( jq -er '.sha256' <<< "${platform}" )  /tmp/devin.tar.gz" && \
    tar -C /usr/local --no-same-owner --no-overwrite-dir -xzf /tmp/devin.tar.gz && \
    rm -rf /tmp/*

ENV HOME=/home/devin

WORKDIR /src
ENTRYPOINT ["devin"]
