FROM to-be-replaced-by-local-ref/base:fedora-44

USER root:root

ENV GOPATH=/root/go \
    GOROOT=/usr/local/go \
    GOTOOLCHAIN=local
ENV PATH=${PATH}:${GOROOT}/bin:${GOPATH}/bin

COPY ./bin/* /usr/local/libexec/glasswing-images/
COPY ./lib/* /usr/local/lib/glasswing-images/

RUN microdnf update -y && \
    microdnf install -y git make gcc && \
    microdnf clean all && \
    rm -rf /var/cache/dnf/*
