FROM to-be-replaced-by-local-ref/golang:1.26

RUN go install github.com/mikefarah/yq/v4@v4.53.2 && \
    go install helm.sh/helm/v4/cmd/helm@v4.2.0 && \
    go install golang.org/x/vuln/cmd/govulncheck@v1.1.4 && \
    go install github.com/tnozicka/ktools/cmd/ktool@v0.0.1 && \
    mkdir -p /go/src/k8s.io/ && \
    pushd /go/src/k8s.io/ && \
    git clone --depth=1 --branch v1.36.1 https://github.com/kubernetes/kubernetes.git && \
    cd ./kubernetes && \
    make WHAT=cmd/kubectl && \
    install -m 0755 /go/src/k8s.io/kubernetes/_output/bin/kubectl "${GOBIN}/kubectl" && \
    popd && \
    rm -rf /go/src/k8s.io/ && \
    go clean -cache -testcache -modcache -fuzzcache && \
    rm -rf /tmp/*
