FROM golang-tools-1.26

RUN dnf install -y procps-ng inotify-tools stress stress-ng vim vim-powerline powerline tmux tmux-powerline tree jq && \
    dnf clean all && \
    rm -rf /var/cache/dnf/*

COPY .bashrc .tmux.conf .vimrc /root/

ENTRYPOINT ["/usr/bin/tmux", "new", "-A"]
