FROM registry.fedoraproject.org/fedora-minimal:43

RUN microdnf install -y procps-ng inotify-tools stress stress-ng && \
    microdnf clean all && \
    rm -rf /var/cache/dnf/*

ENTRYPOINT ["/usr/bin/bash"]
