#!/bin/sh

cat <<EOF
This is a S2I Go ${GO_VERSION} CentOS 7 base image:
To use it, install S2I: https://github.com/openshift/source-to-image
Sample invocation:
$ s2i build https://github.com/openshift-s2i/s2i-go.git \\
    --context-dir=/${GO_VERSION}/test/test-app/ tnozicka/golang-centos7 go-test-app
You can then run the resulting image via:
$ docker run -p 5000:5000 go-test-app
EOF
