name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'
    types:
    - opened
    - edited
    - reopened
    - synchronize
  merge_group:
  schedule:
  - cron:  '0 19 * * *'
  workflow_dispatch:  # Allow manual triggering

permissions:
  id-token: write
  contents: read
  packages: write

env:
  retention_days: 90
  CI_PROMOTE: false

jobs:
  build:
    name: Build images (${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        include:
        - arch: amd64
          runner: ubuntu-24.04
        - arch: arm64
          runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 60
    steps:
    - name: Check out code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags so git describe works.

    - name: Set CI image registry
      shell: bash
      run: echo "IMAGE_REPO_REF_CI=ghcr.io/${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"

    - name: Log in to CI container image registry
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -euEo pipefail +x
        shopt -s inherit_errexit

        echo "${GITHUB_TOKEN}" | buildah login "${{ env.IMAGE_REPO_REF_CI }}" -u="${GITHUB_ACTOR}" --password-stdin

    - name: Build images
      shell: bash
      run: |
        set -euExo pipefail
        shopt -s inherit_errexit

        arch='${{ matrix.arch }}'
        repo_ref="${{ env.IMAGE_REPO_REF_CI }}"
        git_revision="$( git rev-parse HEAD )"
        suffix='${{ github.run_number }}-${{ github.run_attempt }}'

        digestfile="$( mktemp )"
        skip_header=true
        while IFS=, read -r context_dir image_tag from_tag extra_args; do
          if "${skip_header}"; then
            skip_header=false
            continue;
          fi

          image_ref="${repo_ref}:${image_tag}-${suffix}-${arch}"
          if [[ -z "${from_tag}" ]]; then
            from_ref=""
          else
            from_ref="${repo_ref}:${from_tag}-${suffix}-${arch}"
          fi

          time buildah build --squash --format=docker \
          --label="org.opencontainers.image.revision=${git_revision}" \
          ${from_ref:+--from="${from_ref}"} \
          --tag="${image_ref}" \
          ${extra_args:+${extra_args}} \
          "${context_dir}"

          buildah push --digestfile="${digestfile}" "${image_ref}"
          echo '' | cat "${digestfile}" -
        done < image-spec.csv

  manifest-lists:
    name: Create manifest lists
    runs-on: ubuntu-24.04
    needs:
    - build
    timeout-minutes: 30
    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Configure promotions
      shell: bash
      if: ${{ contains(fromJSON('["push", "schedule"]'), github.event_name) }}
      run: |
        set -euEo pipefail +x
        shopt -s inherit_errexit

        echo "CI_PROMOTE=true" | tee -a "${GITHUB_ENV}"

    - name: Set CI image registry
      shell: bash
      run: echo "IMAGE_REPO_REF_CI=ghcr.io/${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"

    - name: Log in to CI container image registry
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -euEo pipefail +x
        shopt -s inherit_errexit

        echo "${GITHUB_TOKEN}" | buildah login "${{ env.IMAGE_REPO_REF_CI }}" -u="${GITHUB_ACTOR}" --password-stdin

    - name: Log in to quay
      shell: bash
      run: |
        set -euEo pipefail +x
        shopt -s inherit_errexit

        echo '${{ secrets.QUAY_PASSWORD }}' | buildah login 'quay.io/tnozicka/images' -u='${{ secrets.QUAY_USER }}' --password-stdin

    - name: Assemble images
      shell: bash
      run: |
        set -euExo pipefail
        shopt -s inherit_errexit

        repo_ref='quay.io/tnozicka/images'
        suffix='${{ github.run_number }}-${{ github.run_attempt }}'

        digestfile="$( mktemp )"
        skip_header=true
        while IFS=, read -r context_dir image_tag from_tag extra_args; do
          if "${skip_header}"; then
            skip_header=false
            continue;
          fi

          ci_image_ref="${{ env.IMAGE_REPO_REF_CI }}:${image_tag}-${suffix}"
          public_image_ref="${repo_ref}:${image_tag}"

          buildah manifest create "${ci_image_ref}"
          for arch in amd64 arm64; do
            buildah manifest add "${ci_image_ref}" "docker://${ci_image_ref}-${arch}"
          done

          buildah manifest push --all --digestfile="${digestfile}" "${ci_image_ref}" "docker://${ci_image_ref}"

          if [[ "${{ env.CI_PROMOTE }}" == "true" ]]; then
            skopeo copy --all --digestfile="${digestfile}" "docker://${ci_image_ref}" "docker://${public_image_ref}"
            echo '' | cat "${digestfile}" -
          fi
        done < image-spec.csv

  gating-tests:
    name: Wait for gating tests
    runs-on: ubuntu-24.04
    needs:
    - build
    - manifest-lists
    if: ${{ always() }}
    steps:
    - name: Fail if any gating dependency failed
      if: ${{ contains(needs.*.result, 'failure') }}
      run: exit 1

  notify-on-failure:
    name: Notify on failure
    runs-on: ubuntu-24.04
    needs:
    - gating-tests
    timeout-minutes: 15
    if: ${{ failure() && github.event_name != 'pull_request' }}
    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Report failures to Slack
      if: ${{ always() }}
      uses: ./.github/actions/notify-failure
      with:
        slack-url: '${{ secrets.SLACK_WEBHOOK_URL }}'
